Financial-Times/o-cookie-message

- bower.json
- demos/src/demo.mustache
- main.scss
- origami.json
- src/scss/_variables.scss
The cookie policy previously defined here was very short but legal have instructed us to update it to the longer version.
So that on mobile this update doesn't take up a large amount of the screen, this PR reduces the font size of the message down to 13px.
This PR also widens the message to the grid width and updates the demo.
Before: 
After:
This will have to be a breaking change as the new design for the cookie message doesn't work with the shorter wordcount of the original message
> Update styles for new cookie policy

- bower.json
- karma.conf.js
- main.scss
The whitespace in this project is a bit bananas and unlike any other
Origami component whitespace (4 spaces instead of a tab)
This commit converts it to be 1 tab indent, except for package.json
and bower.json which will get automatically rewritten as 2 spaces
by bower and npm, and circle.yml for which tabs are invalid.
> Convert whitespace

- src/js/cookieMessage.js
Legal have specified that this cookie message should reappear every
three months.
This commit converts the saved value from a 1 to a timestamp and then
checks the timestamp is within the last three months.
> Make cookie message reappear every three months

- main.scss
- src/js/cookieMessage.js
This commit removes some erroneous padding which was stopping the
cookie message from lining up with the other items on the page
at small widths (where the gutters are smaller)
This commit also fixes the alignment of the close button to line
up with the other edge of the banner properly.
BEFORE
AFTER
> Fix alignment

- .gitignore
- karma.conf.js
- package.json
- test/oCookieMessage.test.js
This PR does nothing except:
- Add sinon
- Add proclaim (and convert existing tests)
- Remove expect
This PR brings o-cookie-message in line with our new testing strategy. @JakeChampion are you happy with these changes before I go ahead and write a bunch more tests for this component?
> Improve tests

- test/helpers/fixtures.js
- test/oCookieMessage.test.js
- test/origamiComponent.test.js
These tests are related to initialisation, and should be very similar for all
Origami components and not specific to oCookieMessage, so I'm putting them in
their own file.
Component specific behaviour can live in oCookieMessgae.test.js
> Add tests for standardised Origami component behaviour

- circle.yml
- package.json
We have OBT as a dev dependency and we cache the `node_modules` folder, using this cached copy of OBT removes ~2 mintues from the execution time on Circle CI.
> Speed up Circle CI execution time by using the cached copy of OBT from the dependencies

- bower.json
- src/js/cookieMessage.js
- test/oCookieMessage.test.js
Currently, o-cookie-message will console error in Safari when o-cookie-
message tries to write to local storage. This commit adds
superstore-sync which wraps local storage but has a workaround for
mobile safari's behaviour.
> Fix errors in Safari's private browsing mode

- circle.yml
- package.json
Reverts Financial-Times/o-cookie-message#24
It seems there was reasoning behind installing obt manually in circle. Circle doesn't have `bower` installed by default.
> Revert "Speed up Circle CI execution time by using the cached copy of OBT from the dependencies"

- bower.json
Switching back to superstore-sync as Alice's forked changes have been merged back upstream
https://github.com/matthew-andrews/superstore-sync/pull/11
> Updating superstore-sync version

- src/js/cookieMessage.js
Focus was getting lost in the cookie message after it was dismissed
> Add tabindex of -1 when cookie message is dismissed

- main.scss
new version on the left, old version on the right, they should look exactly the same
> stop using overly generic oNormaliseHTML include

- README.md
- src/js/cookieMessage.js
- test/oCookieMessage.test.js
Also:-
- ✨ *Bonus:* adds missing test for `oCookieMessage.ready` event.
- ✨ *Bonus:* centralising some repeated logic that gets the message element.
Unsolicited feedback:-
- The static vs. instance method split doesn't seem particularly logical to me.  It seems like the module is trying quite hard to be able to support being instantiated multiple times but then not quite managing it.  I've tried to stick to the pattern of everything being a static method.  But is there a long term goal to make it work correctly if instantiated multiple times?
> Implements oCookieMessage.accepted event on cookie accepted

- src/js/cookieMessage.js
Inappropriate use of `this` causing errors. Unable to dismiss cookie notice.
```document.querySelector('[data-o-component="o-cookie-message-close"]').addEventListener('click', this.flagUserAsConsentingToCookies);```
> Fix cookie dismiss.

- main.scss
- src/js/cookieMessage.js
- src/scss/_variables.scss
Addresses the tweaks requested in https://github.com/Financial-Times/o-cookie-message/issues/48
Desktop before:
Desktop after
Mobile before
Mobile after
Closes #48
> Design tweaks

- src/scss/_mixins.scss
The secondary action now sits above the primary action regardless of
whether the button is standard or alternative.
> Make the small size buttons consistent

- src/js/cookie-message.js
This caters for more of the FT's domains, specifically better catering
for sites which live on a subdomain of `ft.com`. so:
- `www.ft.com` defaults to `ft.com`
- `ftalphaville.ft.com` defaults to `ft.com`
- `www.thebanker.com` defaults to `thebanker.com`
> Provide better domain defaults

- package-lock.json
- src/js/cookie-message.js
- test/helpers/fixtures.js
So that it works with specialist titles not on the ft.com domain:
- change manage cookies path
- switch the fallback accept around with the default accept url
- replace using a RegEx, so we are covered for subdomains as well as www
> use correct path for manage cookies page

- src/js/cookie-message.js
- test/helpers/fixtures.js
The manage my cookies link should point to different routes:
- `manage-cookies`, for ft.com domains
- `cookies`, for non-ft.com domains
Apologies for the oversight. Could you please review and release asap? 🙌
> fix the white-label manage cookies link

- bower.json
- main.scss
- src/scss/_mixins.scss
- src/scss/_privacy-policy-message.scss
o-typography was used but not defined in bower.json.
o-spacing functions replace:
- oTypographyMargin
- oTypographyPadding
- oTypographySpacingSize
Although this introduced a new dependency, o-spacing is new and should not be considered breaking.
> Introduce o-spacing and make o-typography dependnecy explicit.

- origami.json
The demos are broken because a new release of o-normalise has happened.
> Add semver range to demo dependencies.

- bower.json
- demos/src/cookie-message.mustache
- demos/src/custom-html-full.mustache
- main.scss
- origami.json
- src/js/cookie-message.js
- src/scss/_mixins.scss
- src/scss/_variables.scss
- test/helpers/fixtures.js
Previously, o-cookie-message used o-banner in a way that is no longer
possible.
sasswise: obanner now provides only a Primary Mixin and doesn't allow the
granular use that was being taken advantage of by o-cookie-message.
jswise: o-banner was being used to generate the html, that has now been replaced by 1
big chunk of innerHTML setting instead.
> say goodbye to banner, 🍪!

- origami.json
- src/js/cookie-message.js
It turns out, in fact, that the previous version of this component allowed
itself to be used without any template at all. Sure, the javascript didn't work
and it wasn't documented at all but we don't know that someone isn't using that
feature and seeing as this is a legal requirement it's probably best to not
change its behaviour during a crunchy time.
> Append created div if no element was passed

- README.md
- demos/src/custom-html-full.mustache
- src/js/cookie-message.js
- src/scss/_mixins.scss
- test/helpers/fixtures.js
The current markup suggests "Cookies on the FT" is the heading of the page 😬 
https://github.com/Financial-Times/o-cookie-message/issues/101
> Replace the cookie message heading with a `h2`.

- test/oCookieMessage.test.js
- test/origamiComponent.test.js
Stop using the magic imports for proclaim and sinon and pull them from the global because that's where Karma has added them. This is required for obt v10 to be released.
> Stop using magic webpack imports

- main.js
- test/oCookieMessage.test.js
- test/origamiComponent.test.js
relative imports require the full path including the extension because browsers use the import name to make a network request and they do not implicitly add a .js file extension if one is missing
> add extension to relative imports to make the code work directly in a browser

- README.md
- main.scss
- src/scss/_mixins.scss
- src/scss/_variables.scss
The following Sass from the README did not work:
```scss
@include oCookieMessage($opts: (
'themes': ('alternative')
));
```
Note for example the action link font size and the missing external link icon from "cookies":
That's because the `alternative` theme builds on the `standard`
theme, with no modifier class `o-message--standard` the `standard`
theme effects all themes.
This commit removes `standard` as a theme and moves its styles
within the `_oCookieMessageBase` mixin, to be output by default
for other themes to build from.
> Remove the standard theme option (move to base styles).

- README.md
- demos/src/custom-html-full.mustache
- demos/src/custom-html.mustache
- src/js/cookie-message.js
- test/helpers/fixtures.js
>The dialog role is used to mark up an HTML based application dialog or window
>that separates content or UI from the rest of the web application or page.
>Dialogs are generally placed on top of the rest of the page content using an
>overlay. Dialogs can be either non-modal (it's still possible to interact with
>content outside of the dialog) or modal (only the content in the dialog can be
>interacted with).
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role
In the future we can use the `dialog` element:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
Users who have implemented custom html or the core experience
will need to update their markup. Customer Products were
already using the dialog role and will do with the move to …
> Use the dialoge role.

- README.md
- demos/src/custom-html-full.mustache
ft.com are moving from `cookies.ft.com` to `www.ft.com` for the manage
cookies page and are going to use relative links. To ensure no
future copy/paste error update the examples in `o-cookie-message`
> Update the manage cookies demo link
